//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LakkaPlaylistTool.fc_res {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Fc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Fc() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LakkaPlaylistTool.fc_res.Fc", typeof(Fc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 100 Man $ Kid - Maboroshi no Teiou Hen (J)	100万美元-幻之帝王篇(日)
        ///10-Yard Fight (J)	10码大战-橄榄球大赛(日)
        ///10-Yard Fight (U)	10码大战-橄榄球大赛(美)
        ///1942 (JU)	1942(日美)
        ///1943 (J)	1943(日)
        ///1943 (U)	1943(美)
        ///1999 - Hore, Mitakotoka! Seikimatsu (J)	1999强手棋(日)
        ///3-D Battles of World Runner, The (U)	3D世界赛跑者(美)
        ///3-in-1 Supergun (C)	3合1枪(日)
        ///4 Nin Uchi Mahjong (J)	4人麻将(日)
        ///720 (U)	滑板720度(美)
        ///8 Eyes (J)	8只眼(日)
        ///8 Eyes (U)	8只眼(美)
        ///&apos;89 Dennou Kyuusei Uranai (J)	89电脑占卜(日)
        ///A Ressha de Ikou (J)	A列车(日)
        ///Aa Yakyuu Jinsei Icchokusen (J)	呜呼!野球人生 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string fc_rom {
            get {
                return ResourceManager.GetString("fc_rom", resourceCulture);
            }
        }
    }
}
