//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LakkaPlaylistTool.md_res {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class md_cn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal md_cn() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LakkaPlaylistTool.md_res.md_cn", typeof(md_cn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 3 Ninjas Kick Back (U)	忍杀三人组(美)
        ///6-Pak (U)
        ///16 Tiles Mahjong (Unl)	十六张麻将(Unl)
        ///16 Ton (J) (Sega Channel)	世嘉频道(日)
        ///36 Great Holes Starring Fred Couples (32X) (E)	高尔夫球(32X)(欧)
        ///36 Great Holes Starring Fred Couples (32X) (JU)	高尔夫球(32X)(日美)
        ///688 Attack Sub (U)	猎杀潜艇(美)
        ///777 Casino (Unl)
        ///A Ressha de Ikou MD - Take the &apos;A&apos; Train (J)	列车!GO(日)
        ///AAAHH!!! Real Monsters (JUE)	真实怪物(日美欧)
        ///Aah! Harimanada (J)	播磨滩相扑(日)
        ///Abrams Battle Tank (JUE) (r01)	坦克大战(日美欧)
        ///Action 52-in-1 (Unl)	动作52合1(Unl)
        ///Addams Family Values (JUE)  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string md_rom {
            get {
                return ResourceManager.GetString("md_rom", resourceCulture);
            }
        }
    }
}
