//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LakkaPlaylistTool.pce_res {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class pce_cn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pce_cn() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LakkaPlaylistTool.pce_res.pce_cn", typeof(pce_cn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 1941 - Counter Attack (Super Grafx) (J) [a]
        ///1941 - Counter Attack (Super Grafx) (J)
        ///1943 Kai (J)	1943改版(日)
        ///21 Emon - Mezase Hotel Ou!! (J)	旅馆王(日)
        ///Adventure Island (J)	神奇男孩(日)
        ///Aero Blasters (J)	空战克星(日)
        ///Aero Blasters (U)	空战克星(美)
        ///After Burner II (J)	冲破火网２(日)
        ///Air Zonk (U)	空中射击(美)
        ///Aldynes (Super Grafx) (J)	霹雳风云(日)
        ///Alien Crush (J)	异形弹珠台(日)
        ///Alien Crush (U)	异形弹珠台(美)
        ///Ankoku Densetsu (J)	暗黑传说(日)
        ///Aoi Blink (J)	青色杜马(日)
        ///Appare Gateball (J)	槌球大赛(日)
        ///Armed Formation F (J)	F武装战机(日)
        ///Artist Tool (J)	绘图工具(日)
        ///A [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string pce_rom {
            get {
                return ResourceManager.GetString("pce_rom", resourceCulture);
            }
        }
    }
}
