//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LakkaPlaylistTool.fba_res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lakka {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lakka() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LakkaPlaylistTool.fba_res.Lakka", typeof(Lakka).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!--FBA shuffle local gamelist file--&gt;
        ///&lt;!--You can edit this file manually--&gt;
        ///&lt;gamelist&gt;
        ///	&lt;game&gt;
        ///		&lt;name&gt;8ballact&lt;/name&gt;
        ///		&lt;source&gt;Eight Ball Action (DK conversion)&lt;/source&gt;
        ///		&lt;translation&gt;抢 8 撞球 (DK 转换版)&lt;/translation&gt;
        ///	&lt;/game&gt;
        ///	&lt;game&gt;
        ///		&lt;name&gt;bagman&lt;/name&gt;
        ///		&lt;source&gt;Bagman&lt;/source&gt;
        ///		&lt;translation&gt;推销员&lt;/translation&gt;
        ///	&lt;/game&gt;
        ///	&lt;game&gt;
        ///		&lt;name&gt;choplift&lt;/name&gt;
        ///		&lt;source&gt;Choplifter (8751 315-5151)&lt;/source&gt;
        ///		&lt;translation&gt;直升机救难 (8751 315-5151)&lt;/translation&gt;
        ///	&lt;/game&gt;
        ///	&lt;game&gt;
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gamelist_cn {
            get {
                return ResourceManager.GetString("gamelist_cn", resourceCulture);
            }
        }
    }
}
