//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LakkaPlaylistTool.sfc_res {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sfc_cn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sfc_cn() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LakkaPlaylistTool.sfc_res.sfc_cn", typeof(sfc_cn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 2020 Super Baseball (J)	超级棒球2020(日)
        ///2020 Super Baseball (U)	超级棒球2020(美)
        ///3 Jigen Kakutou Ballz (J) (Sample)
        ///3 Jigen Kakutou Ballz (J)
        ///3 Ninjas Kick Back (U)	忍者好小子(美)
        ///3x3 Eyes - Juuma Houkan (J)
        ///3x3 Eyes - Seima Kourinden (J)
        ///4 Nin Shougi (J)
        ///46 Okunen Monogatari - Harukanaru Eden he (J)
        ///7th Saga, The (U)
        ///90 Minutes - European Prime Goal (E) (Beta)	90分钟欧洲足球(欧)(测试版)
        ///90 Minutes - European Prime Goal (E)	90分钟欧洲足球(欧)
        ///&apos;96 Zenkoku Koukou Soccer Senshuken (J)
        ///AAAHH!!! Real Monsters (E)	怪物三人行(欧)
        ///AAAHH!! [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string sfc_rom {
            get {
                return ResourceManager.GetString("sfc_rom", resourceCulture);
            }
        }
    }
}
